# Generated by Django 5.2.5 on 2025-08-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Feminine', 'Feminine'), ('Masculine', 'Masculine'), ('Childish', 'Childish')], max_length=50),
        ),
    ]
